{
  lib,
  stdenv,
  fetchurl,
  gettext,
  attr,
  vmTools,
  acl,
  perl,
  coreutils,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

stdenv.mkDerivation rec {
  pname = "acl";
  version = "2.3.2";

  src = fetchurl {
    url = "mirror://savannah/acl/acl-${version}.tar.gz";
    hash = "sha256-XyvbrWKXB6p9hcYj+ZSqih0t7FWnPeUgW6wL9gWKL3w=";
  };

  outputs = [
    "bin"
    "dev"
    "out"
    "man"
    "doc"
  ];

  nativeBuildInputs = [ gettext ];
  buildInputs = [ attr ];

  postPatch = ''
    patchShebangs .
  '';

  passthru.tests.vmTest =
    # Can't run this within a VM because tests require root access
    # Can't easily use a standard VM test because we need to have access to intermediate build results
    vmTools.runInLinuxVM (
      acl.overrideAttrs (old: {
        pname = old.pname + "-tests";
        postPatch = old.postPatch or "" + ''
          # The runwrapper uses LD_PRELOAD to override available user/groups
          substituteInPlace Makefile.in --replace-fail \
            'TEST_LOG_COMPILER = $(srcdir)/test/runwrapper' \
            'TEST_LOG_COMPILER = $(srcdir)/test/run'
        '';
        nativeCheckInputs = old.nativeCheckInputs or [ ] ++ [
          perl
          # By default `ls` would come from bootstrap tools,
          # which doesn't support showing ACLs, which the tests rely on
          coreutils
        ];
        preCheck = ''
          cp test/test.passwd /etc/passwd
          cp test/test.group /etc/group
        '';
        doCheck = true;
        outputs = [ "out" ];
        installPhase = ''
          touch $out
        '';
      })
    );

  meta = with lib; {
    inherit (attr.meta) platforms badPlatforms;
    homepage = "https://savannah.nongnu.org/projects/acl";
    description = "Library and tools for manipulating access control lists";
    license = licenses.gpl2Plus;
  };
}
